package application;


import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.ToggleGroup;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.layout.AnchorPane;

import javafx.scene.control.RadioButton;

public class InventoryController {
	@FXML
	private AnchorPane orderPagePane;
	@FXML
	private RadioButton pink;
	@FXML
	private ToggleGroup color;
	@FXML
	private RadioButton black;
	@FXML
	private RadioButton grey;
	@FXML
	private RadioButton blue;
	@FXML
	private Button clearButton;
	@FXML
	private Button addButton;
	@FXML
	private ComboBox sizeComboBox;

	// Event Listener on Button[#clearButton].onAction
	@FXML
	public void clearButtonClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#addButton].onAction
	@FXML
	public void addButtonClicked(ActionEvent event) {
		// TODO Autogenerated
	}
}
